site_name: Mundo Gamer

nav:
  - Inicio: index.md
  - Géneros: generos.md
  - Consolas: consolas.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true